export const states: Array<{ name: string; abbreviation: string }> = [
	{ name: "Alabama", abbreviation: "AL" },
	{ name: "Alaska", abbreviation: "AK" },
	{ name: "Arizona", abbreviation: "AZ" },
	{ name: "Arkansas", abbreviation: "AR" },
	{ name: "California", abbreviation: "CA" },
	{ name: "Colorado", abbreviation: "CO" },
	{ name: "Connecticut", abbreviation: "CT" },
	{ name: "Delaware", abbreviation: "DE" },
	{ name: "Florida", abbreviation: "FL" },
	{ name: "Georgia", abbreviation: "GA" },
	{ name: "Hawaii", abbreviation: "HI" },
	{ name: "Idaho", abbreviation: "ID" },
	{ name: "Illinois", abbreviation: "IL" },
	{ name: "Indiana", abbreviation: "IN" },
	{ name: "Iowa", abbreviation: "IA" },
	{ name: "Kansas", abbreviation: "KS" },
	{ name: "Kentucky", abbreviation: "KY" },
	{ name: "Louisiana", abbreviation: "LA" },
	{ name: "Maine", abbreviation: "ME" },
	{ name: "Maryland", abbreviation: "MD" },
	{ name: "Massachusetts", abbreviation: "MA" },
	{ name: "Michigan", abbreviation: "MI" },
	{ name: "Minnesota", abbreviation: "MN" },
	{ name: "Mississippi", abbreviation: "MS" },
	{ name: "Missouri", abbreviation: "MO" },
	{ name: "Montana", abbreviation: "MT" },
	{ name: "Nebraska", abbreviation: "NE" },
	{ name: "Nevada", abbreviation: "NV" },
	{ name: "New Hampshire", abbreviation: "NH" },
	{ name: "New Jersey", abbreviation: "NJ" },
	{ name: "New Mexico", abbreviation: "NM" },
	{ name: "New York", abbreviation: "NY" },
	{ name: "North Carolina", abbreviation: "NC" },
	{ name: "North Dakota", abbreviation: "ND" },
	{ name: "Ohio", abbreviation: "OH" },
	{ name: "Oklahoma", abbreviation: "OK" },
	{ name: "Oregon", abbreviation: "OR" },
	{ name: "Pennsylvania", abbreviation: "PA" },
	{ name: "Rhode Island", abbreviation: "RI" },
	{ name: "South Carolina", abbreviation: "SC" },
	{ name: "South Dakota", abbreviation: "SD" },
	{ name: "Tennessee", abbreviation: "TN" },
	{ name: "Texas", abbreviation: "TX" },
	{ name: "Utah", abbreviation: "UT" },
	{ name: "Vermont", abbreviation: "VT" },
	{ name: "Virginia", abbreviation: "VA" },
	{ name: "Washington", abbreviation: "WA" },
	{ name: "West Virginia", abbreviation: "WV" },
	{ name: "Wisconsin", abbreviation: "WI" },
	{ name: "Wyoming", abbreviation: "WY" },
];

export const countries: Array<{ name: string; country_code: string }> = [
	{ name: "United States of America", country_code: "US" },
	{ name: "Afghanistan", country_code: "AF" },
	{ name: "Albania", country_code: "AL" },
	{ name: "Algeria", country_code: "DZ" },
	{ name: "Andorra", country_code: "AD" },
	{ name: "Angola", country_code: "AO" },
	{ name: "Antigua and Barbuda", country_code: "AG" },
	{ name: "Argentina", country_code: "AR" },
	{ name: "Armenia", country_code: "AM" },
	{ name: "Australia", country_code: "AU" },
	{ name: "Austria", country_code: "AT" },
	{ name: "Azerbaijan", country_code: "AZ" },
	{ name: "Bahamas", country_code: "BS" },
	{ name: "Bahrain", country_code: "BH" },
	{ name: "Bangladesh", country_code: "BD" },
	{ name: "Barbados", country_code: "BB" },
	{ name: "Belarus", country_code: "BY" },
	{ name: "Belgium", country_code: "BE" },
	{ name: "Belize", country_code: "BZ" },
	{ name: "Benin", country_code: "BJ" },
	{ name: "Bhutan", country_code: "BT" },
	{ name: "Bolivia", country_code: "BO" },
	{ name: "Bosnia and Herzegovina", country_code: "BA" },
	{ name: "Botswana", country_code: "BW" },
	{ name: "Brazil", country_code: "BR" },
	{ name: "Brunei Darussalam", country_code: "BN" },
	{ name: "Bulgaria", country_code: "BG" },
	{ name: "Burkina Faso", country_code: "BF" },
	{ name: "Burundi", country_code: "BI" },
	{ name: "Cabo Verde", country_code: "CV" },
	{ name: "Cambodia", country_code: "KH" },
	{ name: "Cameroon", country_code: "CM" },
	{ name: "Canada", country_code: "CA" },
	{ name: "Central African Republic", country_code: "CF" },
	{ name: "Chad", country_code: "TD" },
	{ name: "Chile", country_code: "CL" },
	{ name: "China", country_code: "CN" },
	{ name: "Colombia", country_code: "CO" },
	{ name: "Comoros", country_code: "KM" },
	{ name: "Congo", country_code: "CG" },
	{ name: "Costa Rica", country_code: "CR" },
	{ name: "Côte d'Ivoire", country_code: "CI" },
	{ name: "Croatia", country_code: "HR" },
	{ name: "Cuba", country_code: "CU" },
	{ name: "Cyprus", country_code: "CY" },
	{ name: "Czech Republic", country_code: "CZ" },
	{ name: "North Korea", country_code: "KP" },
	{ name: "Democratic Republic of the Congo", country_code: "CD" },
	{ name: "Denmark", country_code: "DK" },
	{ name: "Djibouti", country_code: "DJ" },
	{ name: "Dominica", country_code: "DM" },
	{ name: "Dominican Republic", country_code: "DO" },
	{ name: "Ecuador", country_code: "EC" },
	{ name: "Egypt", country_code: "EG" },
	{ name: "El Salvador", country_code: "SV" },
	{ name: "Equatorial Guinea", country_code: "GQ" },
	{ name: "Eritrea", country_code: "ER" },
	{ name: "Estonia", country_code: "EE" },
	{ name: "Eswatini", country_code: "SZ" },
	{ name: "Ethiopia", country_code: "ET" },
	{ name: "Fiji", country_code: "FJ" },
	{ name: "Finland", country_code: "FI" },
	{ name: "France", country_code: "FR" },
	{ name: "Gabon", country_code: "GA" },
	{ name: "Gambia", country_code: "GM" },
	{ name: "Georgia", country_code: "GE" },
	{ name: "Germany", country_code: "DE" },
	{ name: "Ghana", country_code: "GH" },
	{ name: "Greece", country_code: "GR" },
	{ name: "Grenada", country_code: "GD" },
	{ name: "Guatemala", country_code: "GT" },
	{ name: "Guinea", country_code: "GN" },
	{ name: "Guinea-Bissau", country_code: "GW" },
	{ name: "Guyana", country_code: "GY" },
	{ name: "Haiti", country_code: "HT" },
	{ name: "Honduras", country_code: "HN" },
	{ name: "Hungary", country_code: "HU" },
	{ name: "Iceland", country_code: "IS" },
	{ name: "India", country_code: "IN" },
	{ name: "Indonesia", country_code: "ID" },
	{ name: "Iran", country_code: "IR" },
	{ name: "Iraq", country_code: "IQ" },
	{ name: "Ireland", country_code: "IE" },
	{ name: "Israel", country_code: "IL" },
	{ name: "Italy", country_code: "IT" },
	{ name: "Jamaica", country_code: "JM" },
	{ name: "Japan", country_code: "JP" },
	{ name: "Jordan", country_code: "JO" },
	{ name: "Kazakhstan", country_code: "KZ" },
	{ name: "Kenya", country_code: "KE" },
	{ name: "Kiribati", country_code: "KI" },
	{ name: "Kuwait", country_code: "KW" },
	{ name: "Kyrgyzstan", country_code: "KG" },
	{ name: "Laos", country_code: "LA" },
	{ name: "Latvia", country_code: "LV" },
	{ name: "Lebanon", country_code: "LB" },
	{ name: "Lesotho", country_code: "LS" },
	{ name: "Liberia", country_code: "LR" },
	{ name: "Libya", country_code: "LY" },
	{ name: "Liechtenstein", country_code: "LI" },
	{ name: "Lithuania", country_code: "LT" },
	{ name: "Luxembourg", country_code: "LU" },
	{ name: "Madagascar", country_code: "MG" },
	{ name: "Malawi", country_code: "MW" },
	{ name: "Malaysia", country_code: "MY" },
	{ name: "Maldives", country_code: "MV" },
	{ name: "Mali", country_code: "ML" },
	{ name: "Malta", country_code: "MT" },
	{ name: "Marshall Islands", country_code: "MH" },
	{ name: "Mauritania", country_code: "MR" },
	{ name: "Mauritius", country_code: "MU" },
	{ name: "Mexico", country_code: "MX" },
	{ name: "Micronesia", country_code: "FM" },
	{ name: "Monaco", country_code: "MC" },
	{ name: "Mongolia", country_code: "MN" },
	{ name: "Montenegro", country_code: "ME" },
	{ name: "Morocco", country_code: "MA" },
	{ name: "Mozambique", country_code: "MZ" },
	{ name: "Myanmar", country_code: "MM" },
	{ name: "Namibia", country_code: "NA" },
	{ name: "Nauru", country_code: "NR" },
	{ name: "Nepal", country_code: "NP" },
	{ name: "Netherlands", country_code: "NL" },
	{ name: "New Zealand", country_code: "NZ" },
	{ name: "Nicaragua", country_code: "NI" },
	{ name: "Niger", country_code: "NE" },
	{ name: "Nigeria", country_code: "NG" },
	{ name: "North Macedonia", country_code: "MK" },
	{ name: "Norway", country_code: "NO" },
	{ name: "Oman", country_code: "OM" },
	{ name: "Pakistan", country_code: "PK" },
	{ name: "Palau", country_code: "PW" },
	{ name: "Panama", country_code: "PA" },
	{ name: "Papua New Guinea", country_code: "PG" },
	{ name: "Paraguay", country_code: "PY" },
	{ name: "Peru", country_code: "PE" },
	{ name: "Philippines", country_code: "PH" },
	{ name: "Poland", country_code: "PL" },
	{ name: "Portugal", country_code: "PT" },
	{ name: "Qatar", country_code: "QA" },
	{ name: "South Korea", country_code: "KR" },
	{ name: "Moldova", country_code: "MD" },
	{ name: "Romania", country_code: "RO" },
	{ name: "Russian Federation", country_code: "RU" },
	{ name: "Rwanda", country_code: "RW" },
	{ name: "Saint Kitts and Nevis", country_code: "KN" },
	{ name: "Saint Lucia", country_code: "LC" },
	{ name: "Saint Vincent and the Grenadines", country_code: "VC" },
	{ name: "Samoa", country_code: "WS" },
	{ name: "San Marino", country_code: "SM" },
	{ name: "Sao Tome and Principe", country_code: "ST" },
	{ name: "Saudi Arabia", country_code: "SA" },
	{ name: "Senegal", country_code: "SN" },
	{ name: "Serbia", country_code: "RS" },
	{ name: "Seychelles", country_code: "SC" },
	{ name: "Sierra Leone", country_code: "SL" },
	{ name: "Singapore", country_code: "SG" },
	{ name: "Slovakia", country_code: "SK" },
	{ name: "Slovenia", country_code: "SI" },
	{ name: "Solomon Islands", country_code: "SB" },
	{ name: "Somalia", country_code: "SO" },
	{ name: "South Africa", country_code: "ZA" },
	{ name: "South Sudan", country_code: "SS" },
	{ name: "Spain", country_code: "ES" },
	{ name: "Sri Lanka", country_code: "LK" },
	{ name: "Sudan", country_code: "SD" },
	{ name: "Suriname", country_code: "SR" },
	{ name: "Sweden", country_code: "SE" },
	{ name: "Switzerland", country_code: "CH" },
	{ name: "Syrian Arab Republic", country_code: "SY" },
	{ name: "Tajikistan", country_code: "TJ" },
	{ name: "Thailand", country_code: "TH" },
	{ name: "Timor-Leste", country_code: "TL" },
	{ name: "Togo", country_code: "TG" },
	{ name: "Tonga", country_code: "TO" },
	{ name: "Trinidad and Tobago", country_code: "TT" },
	{ name: "Tunisia", country_code: "TN" },
	{ name: "Turkey", country_code: "TR" },
	{ name: "Turkmenistan", country_code: "TM" },
	{ name: "Tuvalu", country_code: "TV" },
	{ name: "Uganda", country_code: "UG" },
	{ name: "Ukraine", country_code: "UA" },
	{ name: "United Arab Emirates", country_code: "AE" },
	{ name: "United Kingdom", country_code: "GB" },
	{ name: "Tanzania", country_code: "TZ" },
	{ name: "Uruguay", country_code: "UY" },
	{ name: "Uzbekistan", country_code: "UZ" },
	{ name: "Vanuatu", country_code: "VU" },
	{ name: "Venezuela", country_code: "VE" },
	{ name: "Vietnam", country_code: "VN" },
	{ name: "Yemen", country_code: "YE" },
	{ name: "Zambia", country_code: "ZM" },
	{ name: "Zimbabwe", country_code: "ZW" },
];
